//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Instrument"",
            ""id"": ""83c4a060-d5a5-421d-841c-5cfdfe39e387"",
            ""actions"": [
                {
                    ""name"": ""C4"",
                    ""type"": ""Button"",
                    ""id"": ""c2b822ef-8bfb-4fef-83b4-b8393f875b6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D4"",
                    ""type"": ""Button"",
                    ""id"": ""64e6ca85-4069-4b21-bfd1-66781732c498"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E4"",
                    ""type"": ""Button"",
                    ""id"": ""4dda5e82-8e7f-4adf-addf-9c857806d057"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F4"",
                    ""type"": ""Button"",
                    ""id"": ""85b6e83f-d9d0-469d-8a2e-d37c14ced592"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G4"",
                    ""type"": ""Button"",
                    ""id"": ""dabc3d11-20de-40fb-8d91-106c1dd4fd21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A4"",
                    ""type"": ""Button"",
                    ""id"": ""8eb2b139-b3ca-4af6-9b1a-ba4da70b3b49"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B4"",
                    ""type"": ""Button"",
                    ""id"": ""50df8668-774f-4dd2-8c99-98eb0acb6b45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C5"",
                    ""type"": ""Button"",
                    ""id"": ""05cb7b72-a66b-4791-9915-d323fc2ad79a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C4Sharp"",
                    ""type"": ""Button"",
                    ""id"": ""e3941e76-f27e-4f4c-b6a9-aa1beaca959c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D4Sharp"",
                    ""type"": ""Button"",
                    ""id"": ""36fd4c47-fcdc-4b35-8145-cd712de3b78a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F4Sharp"",
                    ""type"": ""Button"",
                    ""id"": ""6c647e7b-2885-41aa-870f-b61046d9a6a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G4Sharp"",
                    ""type"": ""Button"",
                    ""id"": ""fd7a9682-ea23-4824-b34e-937075292250"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A4Sharp"",
                    ""type"": ""Button"",
                    ""id"": ""c314539f-8a3d-45fc-9f68-62ac757144dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C5Sharp"",
                    ""type"": ""Button"",
                    ""id"": ""549dc78d-bb7d-43cc-81c6-7c363c1e03a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5e3e4cdb-ddc0-4afb-b440-29fec3b6ff6c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76a30e1f-be51-40e8-a153-60f1796e9a22"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33476737-9386-4a4c-9d41-d0dc489dbbfc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43fb1a33-ac08-46d6-a582-c7a72e46bd57"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6496fbbb-52a3-4ca4-af91-be4645079470"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cfc106d-3ab5-4cd2-a0aa-76f8dbe4bd10"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4e8f2b2-eb98-44d3-8a08-df81ef7b19bc"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c4ac425-7557-456e-8526-1fd0bd0e377b"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c424c5da-5699-4cb4-9e7d-f94a11e749c8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C4Sharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92884957-86ec-4892-8451-15476c121cc8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D4Sharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d18d4fc5-9f8d-4840-946e-7ff6d485dae4"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F4Sharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cf477c7-aaef-4db5-b020-e154bd37d3d8"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G4Sharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e15c471-a22d-49b6-a828-8f308ac7ae41"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A4Sharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87383bb1-6279-4432-b38b-45888da84e0a"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C5Sharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Instrument
        m_Instrument = asset.FindActionMap("Instrument", throwIfNotFound: true);
        m_Instrument_C4 = m_Instrument.FindAction("C4", throwIfNotFound: true);
        m_Instrument_D4 = m_Instrument.FindAction("D4", throwIfNotFound: true);
        m_Instrument_E4 = m_Instrument.FindAction("E4", throwIfNotFound: true);
        m_Instrument_F4 = m_Instrument.FindAction("F4", throwIfNotFound: true);
        m_Instrument_G4 = m_Instrument.FindAction("G4", throwIfNotFound: true);
        m_Instrument_A4 = m_Instrument.FindAction("A4", throwIfNotFound: true);
        m_Instrument_B4 = m_Instrument.FindAction("B4", throwIfNotFound: true);
        m_Instrument_C5 = m_Instrument.FindAction("C5", throwIfNotFound: true);
        m_Instrument_C4Sharp = m_Instrument.FindAction("C4Sharp", throwIfNotFound: true);
        m_Instrument_D4Sharp = m_Instrument.FindAction("D4Sharp", throwIfNotFound: true);
        m_Instrument_F4Sharp = m_Instrument.FindAction("F4Sharp", throwIfNotFound: true);
        m_Instrument_G4Sharp = m_Instrument.FindAction("G4Sharp", throwIfNotFound: true);
        m_Instrument_A4Sharp = m_Instrument.FindAction("A4Sharp", throwIfNotFound: true);
        m_Instrument_C5Sharp = m_Instrument.FindAction("C5Sharp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Instrument
    private readonly InputActionMap m_Instrument;
    private IInstrumentActions m_InstrumentActionsCallbackInterface;
    private readonly InputAction m_Instrument_C4;
    private readonly InputAction m_Instrument_D4;
    private readonly InputAction m_Instrument_E4;
    private readonly InputAction m_Instrument_F4;
    private readonly InputAction m_Instrument_G4;
    private readonly InputAction m_Instrument_A4;
    private readonly InputAction m_Instrument_B4;
    private readonly InputAction m_Instrument_C5;
    private readonly InputAction m_Instrument_C4Sharp;
    private readonly InputAction m_Instrument_D4Sharp;
    private readonly InputAction m_Instrument_F4Sharp;
    private readonly InputAction m_Instrument_G4Sharp;
    private readonly InputAction m_Instrument_A4Sharp;
    private readonly InputAction m_Instrument_C5Sharp;
    public struct InstrumentActions
    {
        private @PlayerInputActions m_Wrapper;
        public InstrumentActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @C4 => m_Wrapper.m_Instrument_C4;
        public InputAction @D4 => m_Wrapper.m_Instrument_D4;
        public InputAction @E4 => m_Wrapper.m_Instrument_E4;
        public InputAction @F4 => m_Wrapper.m_Instrument_F4;
        public InputAction @G4 => m_Wrapper.m_Instrument_G4;
        public InputAction @A4 => m_Wrapper.m_Instrument_A4;
        public InputAction @B4 => m_Wrapper.m_Instrument_B4;
        public InputAction @C5 => m_Wrapper.m_Instrument_C5;
        public InputAction @C4Sharp => m_Wrapper.m_Instrument_C4Sharp;
        public InputAction @D4Sharp => m_Wrapper.m_Instrument_D4Sharp;
        public InputAction @F4Sharp => m_Wrapper.m_Instrument_F4Sharp;
        public InputAction @G4Sharp => m_Wrapper.m_Instrument_G4Sharp;
        public InputAction @A4Sharp => m_Wrapper.m_Instrument_A4Sharp;
        public InputAction @C5Sharp => m_Wrapper.m_Instrument_C5Sharp;
        public InputActionMap Get() { return m_Wrapper.m_Instrument; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InstrumentActions set) { return set.Get(); }
        public void SetCallbacks(IInstrumentActions instance)
        {
            if (m_Wrapper.m_InstrumentActionsCallbackInterface != null)
            {
                @C4.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC4;
                @C4.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC4;
                @C4.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC4;
                @D4.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnD4;
                @D4.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnD4;
                @D4.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnD4;
                @E4.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnE4;
                @E4.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnE4;
                @E4.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnE4;
                @F4.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnF4;
                @F4.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnF4;
                @F4.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnF4;
                @G4.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnG4;
                @G4.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnG4;
                @G4.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnG4;
                @A4.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnA4;
                @A4.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnA4;
                @A4.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnA4;
                @B4.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnB4;
                @B4.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnB4;
                @B4.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnB4;
                @C5.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC5;
                @C5.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC5;
                @C5.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC5;
                @C4Sharp.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC4Sharp;
                @C4Sharp.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC4Sharp;
                @C4Sharp.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC4Sharp;
                @D4Sharp.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnD4Sharp;
                @D4Sharp.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnD4Sharp;
                @D4Sharp.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnD4Sharp;
                @F4Sharp.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnF4Sharp;
                @F4Sharp.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnF4Sharp;
                @F4Sharp.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnF4Sharp;
                @G4Sharp.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnG4Sharp;
                @G4Sharp.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnG4Sharp;
                @G4Sharp.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnG4Sharp;
                @A4Sharp.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnA4Sharp;
                @A4Sharp.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnA4Sharp;
                @A4Sharp.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnA4Sharp;
                @C5Sharp.started -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC5Sharp;
                @C5Sharp.performed -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC5Sharp;
                @C5Sharp.canceled -= m_Wrapper.m_InstrumentActionsCallbackInterface.OnC5Sharp;
            }
            m_Wrapper.m_InstrumentActionsCallbackInterface = instance;
            if (instance != null)
            {
                @C4.started += instance.OnC4;
                @C4.performed += instance.OnC4;
                @C4.canceled += instance.OnC4;
                @D4.started += instance.OnD4;
                @D4.performed += instance.OnD4;
                @D4.canceled += instance.OnD4;
                @E4.started += instance.OnE4;
                @E4.performed += instance.OnE4;
                @E4.canceled += instance.OnE4;
                @F4.started += instance.OnF4;
                @F4.performed += instance.OnF4;
                @F4.canceled += instance.OnF4;
                @G4.started += instance.OnG4;
                @G4.performed += instance.OnG4;
                @G4.canceled += instance.OnG4;
                @A4.started += instance.OnA4;
                @A4.performed += instance.OnA4;
                @A4.canceled += instance.OnA4;
                @B4.started += instance.OnB4;
                @B4.performed += instance.OnB4;
                @B4.canceled += instance.OnB4;
                @C5.started += instance.OnC5;
                @C5.performed += instance.OnC5;
                @C5.canceled += instance.OnC5;
                @C4Sharp.started += instance.OnC4Sharp;
                @C4Sharp.performed += instance.OnC4Sharp;
                @C4Sharp.canceled += instance.OnC4Sharp;
                @D4Sharp.started += instance.OnD4Sharp;
                @D4Sharp.performed += instance.OnD4Sharp;
                @D4Sharp.canceled += instance.OnD4Sharp;
                @F4Sharp.started += instance.OnF4Sharp;
                @F4Sharp.performed += instance.OnF4Sharp;
                @F4Sharp.canceled += instance.OnF4Sharp;
                @G4Sharp.started += instance.OnG4Sharp;
                @G4Sharp.performed += instance.OnG4Sharp;
                @G4Sharp.canceled += instance.OnG4Sharp;
                @A4Sharp.started += instance.OnA4Sharp;
                @A4Sharp.performed += instance.OnA4Sharp;
                @A4Sharp.canceled += instance.OnA4Sharp;
                @C5Sharp.started += instance.OnC5Sharp;
                @C5Sharp.performed += instance.OnC5Sharp;
                @C5Sharp.canceled += instance.OnC5Sharp;
            }
        }
    }
    public InstrumentActions @Instrument => new InstrumentActions(this);
    public interface IInstrumentActions
    {
        void OnC4(InputAction.CallbackContext context);
        void OnD4(InputAction.CallbackContext context);
        void OnE4(InputAction.CallbackContext context);
        void OnF4(InputAction.CallbackContext context);
        void OnG4(InputAction.CallbackContext context);
        void OnA4(InputAction.CallbackContext context);
        void OnB4(InputAction.CallbackContext context);
        void OnC5(InputAction.CallbackContext context);
        void OnC4Sharp(InputAction.CallbackContext context);
        void OnD4Sharp(InputAction.CallbackContext context);
        void OnF4Sharp(InputAction.CallbackContext context);
        void OnG4Sharp(InputAction.CallbackContext context);
        void OnA4Sharp(InputAction.CallbackContext context);
        void OnC5Sharp(InputAction.CallbackContext context);
    }
}
